function img =trimImage(image)
    siz=size(image);
    offsetTop=0;
    offsetBottom=0;
    offsetLeft=0;
    offsetRight=0;
    for(n=1:siz(1))
        if(sum(image(n,:),2)==siz(2))
            offsetTop=offsetTop+1;
        else
            break;
        end;
    end;
    for(n=siz(1):-1:1)
        if(sum(image(n,:),2)==siz(2))
            offsetBottom=offsetBottom+1;
        else
            break;
        end;
    end;

    for(n=1:siz(2))
        if(sum(image(:,n),1)==siz(1))
            offsetLeft=offsetLeft+1;
        else
            break;
        end;
    end;
    for(n=siz(2):-1:1)
        if(sum(image(:,n),1)==siz(1))
            offsetRight=offsetRight+1;
        else
            break;
        end;
    end;
    top=offsetTop+1;
    bottom=siz(1)-offsetBottom;
    left=offsetLeft+1;
    right=siz(2)-offsetRight;
    img=image(top:bottom,left:right);
end